appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: prrU/ku298geedmebikk26wu7dexDTI/UYZ61/B3a75VxxUTyV/GTAvurmTteq4h3vJzCPh0nTRkbT0VJV38kLdgeIHw55lGSxEStjL7XfWEZh9roLdZ/3NrfsJL33eCF1FrOvTgS+og2khoO2FG/6BDXGCxz5X+InVOhVKQSY+w+Wd9il+CoVdl/yjxEY9PPX0GJ1xAE25452bxZdCgdLDPPrmIeKy6LLakqMvSr/JWcdTk1LSEKzQilX0Uf7+CmWujE6sgp0Qj2ZPqobXcYus2Af6AhQCAUlqh2+9zFKBELZNTXtcRvdPtiKc3tWCeV3RVraGoTjZqUx4ngXE0brJ+ERj+5lIxsG4tGGIgc/OA36HEUHM9OLWPjkhYfzMyCsxJP/ElSypY44ZS+J+4qP5bChdd7eSusgRBvJBLF6Vek3aPZY73P7mYb4WezvUkUK47ClNLSqbSPRcjcY8hWHdOYI+9Y3ZglDu0lhYUdGwZUa3ICbbkCbEiteySk+uxQRWW//H4+JOrfWuiNTgeom1gocWyOLqiSVelRrNeIs56ivY3xHP6m8VN9Kg0hGu6HhbPw4wGhQjQ14lK4yROtjO4QBbOG7V2tfagzu5VzRFfMcVu5mqQl4DLcMyU7lh1jlj1sV/wV0B64kgc6hVcgvzFLZ3a2NCISL4vQrkOvks=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
